### ISSUE TITLE
Requires authentication

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-data-iana#5]
GH API returrns "Requires authentication" message. May be token is expaired. @ronaldtse could you chek the GH token?
https://github.com/relaton/relaton-data-iana/actions/runs/4820830663/jobs/8585864400#step:5:9

**Comment by ronaldtse** [comment]
I think this may be related to the recent change by @CAMOBAP on the shared workflow. In the **relaton** repositories, the token secret is 
<img width="257" alt="Screenshot 2023-04-28 at 1 25 25 PM" src="https://user-images.githubusercontent.com/11865/235053940-b52c7410-5982-47eb-b0b2-aba57cec149e.png">

The token is currently valid.

Ping @CAMOBAP for help.

**Comment by CAMOBAP** [comment]
@ronaldtse it doesn't seem that it's related to my changes in the shared workflow:
- my changes were done 3 days ago
- workflow in this repo starts failing 2 weeks ago

So it more looks like permissings in GITHUB_TOKEN changed

But I have changed the logic and now RELATON_CI_PAT used instead GITHUB_TOKEN https://github.com/relaton/relaton-data-iana/pull/4 and it works now https://github.com/relaton/relaton-data-iana/actions/runs/4840540231

@andrew2net could you please have look at https://github.com/relaton/relaton-data-iana/pull/4

**Comment by ronaldtse** [comment]
Interesting. But I think GITHUB_TOKEN never had permission to update the repo itself unless the permissions were requested in the GHA workflow?

**Comment by CAMOBAP** [comment]
@ronaldtse actually it had, but it has an interesting side effect -  such commits will never trigger any workflow. This is why we often need PAT token
